export const SearchActions = {
  ADD_SUBURB:           'ADD_SUBURB',
  ADD_ADDRESS:          'ADD_ADDRESS',
  REMOVE_SUBURB:        'REMOVE_SUBURB',
  REMOVE_ADDRESS:       'REMOVE_ADDRESS',
  SET_EDUCATION_LEVEL:  'SELECT_EDUCATION_LEVEL',
  SET_SELECTIVE_LEVEL:  'SELECT_SELECTIVE_LEVEL',
}

